services:
  server:
    container_name: web-bubble-sheet
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18020:18020"
    env_file:
      - ./server/.env

networks:
  web-bubble-sheet-network:
    external: true
