services:
  app:
    container_name: web-bubble-sheet
    image: ghcr.io/coccoto/web-bubble-sheet:latest
    restart: unless-stopped
    ports:
      - "18020:18020"
    env_file:
      - ./server/.env
    networks:
      - web-bubble-sheet-network

networks:
  web-bubble-sheet-network:
    name: web-bubble-sheet-network
    external: true
